### ISSUE TITLE
Handle layout key in frontmatter

### ISSUE THREAD

**Issue by johno** [c8r/markdown#79]
After some discussion with @timneutkens and @jxnblk we think it makes most sense to allow layout to be optionally specified in frontmatter.

```yaml
---
title: Awesome Page
slug: /awesome
layout: ./PageLayout
team:
  - jxn
  - mrmrs
  - johno
---
```

Resulting in, when `layout` is defined, the result would be something similar to:

```jsx
import PageLayout from './PageLayout'

// ... stuff

export default PostLayout(frontmatter)(Markdown)
```

Something to consider: Should a layout be a HOC or standard component?

**Comment by rauchg** [comment]
Also, `layout` blending in as a 'regular prop' is a bit dangerous. It's not obvious that it's special. Maybe it should be `Layout`? `_layout`? 😨

**Comment by timneutkens** [comment]
Another option is nesting it under another property name, like mdxSettings or something.

**Comment by johnotander** [comment]
Very valid points.

I wonder if we want some type of `_mdx` key that all potential MDX config lives under. For now it's really only the `layout`, but it'd provide the ability to layer in new config if it ever became necessary.

```yml
---
title: Awesome Page
slug: /awesome
team:
  - jxn
  - mrmrs
  - johno
_mdx:
  layout: ./PageLayout
---
```
